### ISSUE TITLE
Make saving the states at each time step to be default

### ISSUE THREAD

**Issue by ytdHuang** [albertomercurio/QuantumToolbox.jl#22]
I noticed that the current `sesolve` and `mesolve` will only return the final state corresponds to the given time list parameter (`tl`). For example,
```julia
> using QuantumToolbox
> H  = sigmaz()
> ψ0 = sqrt(0.5) * (basis(2, 0) + basis(2, 1))
> tlist = 0:1:10
> sol = sesolve(H, ψ0, tlist)
> sol.times
# this returns a vector which contains single value 10 (last element in tlist)
> sol.states
# this returns a vector which contains only the final state
```
I expect to obtain:
```julia
> sol.times
# all the elements in tlist
> sol.states
# all the states corresponding to each time step
```

I'm not familiar with the `DiffEqCallbacks.jl` API, but I think it must be related to the parameter `saveat`, as said in the docs from `DifferentialEquations.jl`:

> `saveat`: Denotes specific times to save the solution at, during the solving phase. **The solver will save at each of the timepoints in this array in the most efficient manner available to the solver.** If only `saveat` is given, then the arguments `save_everystep` and `dense` are `false` by default. If `saveat` is given a number, then it will automatically expand to `tspan[1]:saveat:tspan[2]`. For methods where interpolation is not possible, `saveat` may be equivalent to `tstops`. The default value is `[]`.

So currently, we need to do it like this
```julia
> sol = sesolve(H, ψ0, tlist; saveat=tlist)
```
which needs to provide the `tlist` twice and becomes a bit redundant.

**Comment by albertomercurio** [comment]
Yes, this was a central question raised during the development of those functions. Finally, I thought that that best default option would be the one that minimizes the use of CPU and RAM. 

In my opinion, storing the intermediate states during the dynamics is not very common. Usually, we calculate the expectation values, which occupy little memory space compared to the full density matrices. This difference increases with the increase of the Hilbert space dimension.

So I decided to save only the final state as a default, with the possibility to change it adding a keyword argument as you did above.

**Comment by ytdHuang** [comment]
Nice point! I was thinking about making it similar to QuTiP. But it's not necessary actually.
