### ISSUE TITLE
Make a logo, possibly using `QuantumToolbox.jl`

### ISSUE THREAD

**Issue by albertomercurio** [albertomercurio/QuantumToolbox.jl#83]
Make a logo for the package, possibly using the `QuantumToolbox.jl` package.

What I have in mind is for example creating the Wigner function a triangular cat state

$$
\ket{\psi} = \ket{\alpha} + \ket{e^{i \frac{2}{3} \pi} \alpha} + \ket{e^{i \frac{4}{3} \pi} \alpha}
$$

and possibly mapping the colors following the Julia logo.

Then, we can add a documentation page demonstrating how this logo was made, showing step by step the code.

**Comment by ytdHuang** [comment]
Good idea !

**Comment by ytdHuang** [comment]
@albertomercurio 

I suggest the background color of the logo to be transparent.

Then, we can prepare two different logo (for light- and dark-theme website), and put it in the folder `docs/src/assets/`. 

The file name must be:
- `logo.png`: logo for ***light-theme website***, maybe with the ***black*** color characters (QuantumToolbox) in the logo
- `logo-dark.png`: logo for ***dark-theme website***, maybe with the ***white*** color characters (QuantumToolbox) in the logo: QuantumToolbox)

In this case, the `Documenter.jl` will automatically detect the logo files if it is located in `docs/src/assets/`.

Also, we can insert the logo to `README.md` by adding the following lines in the beginning:
```
![Fancy logo](./docs/src/assets/logo-dark.png#gh-dark-mode-only)
![Fancy logo](./docs/src/assets/logo.png#gh-light-mode-only)
```
